import numpy as np
import os
from joblib import Parallel, delayed
from scipy.linalg import eigh
from sklearn.linear_model import LinearRegression, Ridge
from Models import get_Pauli_X, get_Pauli_Z, Ising
from Density_matrix import trace_1, mixed_density_matrix

# --- 1. Data Generation (Source of Truth) ---
def generate_mg_dataset():
    """Generates the Mackey-Glass series exactly as provided."""
    sigma, tau_MG, steps = 0.1, 17, 140000
    A = np.zeros(steps)
    A[0] = 1.2
    delay_idx = int(tau_MG / sigma)

    for i in range(steps - 1):
        delayed_val = A[i - delay_idx] if i >= delay_idx else 1.2
        A[i+1] = A[i] + sigma * ((0.2 * delayed_val) / (1 + delayed_val**10) - 0.1 * A[i])

    # Subsampling and normalization
    A_sub = A[10000:]
    y = A_sub[::10]
    y = (y - np.min(y)) / (np.max(y) - np.min(y))
    y = 0.1 + 0.8 * y 
    return y

# --- 2. Simulation Logic ---
def run_stability_test(h_val, seed, data_slices):
    s_washout, s_train, y_train, y_test_target = data_slices
    rng = np.random.default_rng(seed)

    # --- Hamiltonian and Operator Setup ---
    # Pre-calculate operators once using Models module
    x_ops = get_Pauli_X(N)
    z_ops = get_Pauli_Z(N)

    # Construct the Ising Hamiltonian
    Hamiltonian, _ = Ising(N, J_val, h_val, rng, x_ops, z_ops)

    # --- Exact Diagonalization (ED) for Time Evolution ---
    # Diagonalizing once allows for extremely fast evolution in the inner loop
    E, U = eigh(Hamiltonian)
    U_dag = U.conj().T

    # Pre-calculate evolution phases
    dt = tau / V
    Phase_dt = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * dt)
    Phase_tau = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * tau)
    
    def evolve(rho_in, phase_mat):
        rho_energy = U_dag @ rho_in @ U
        return U @ (rho_energy * phase_mat) @ U_dag

    def input_map(rho_in, s, N):
        """Map input s to the first spin and trace out the rest using the module's reshape trick."""
        psi_s = np.array([np.sqrt(1-s), np.sqrt(s)], dtype=complex)
        rho_s = np.outer(psi_s, psi_s.conj())
        # Use optimized partial trace from Density_matrix
        rho_rest = trace_1(rho_in, N)
        return np.kron(rho_s, rho_rest)

    # --- Training Phase ---
    # Initial mixed state generated by the module
    rho = mixed_density_matrix(10, 2, N, rng)
    X_features = np.zeros((tr_len, N * V))

    # Pre-calculate diagonals of Z for fast trace-less expectation values
    z_diags = [op.diagonal() for op in z_ops]

    for s in s_washout:
        rho = evolve(input_map(rho, s, N), Phase_tau)

    for k in range(tr_len):
        rho = input_map(rho, s_train[k], N)
        for v in range(V):
            rho = evolve(rho, Phase_dt)
            # Fast expectation value: Tr(rho @ Z) = sum(diag(rho) * diag(Z))
            rho_diag = rho.diagonal()
            for n in range(N):
                X_features[k, v*N + n] = np.real(np.sum(rho_diag * z_diags[n]))

    # Post-processing: Normalization and small noise for stability
    X_features = (X_features + 1) / 2
    X_features += rng.uniform(-1e-5, 1e-5, X_features.shape)

    model = Ridge(alpha=1e-4).fit(X_features, y_train)

    # --- Evaluation (The Probe) ---
    y_out = np.zeros(te_len)
    y_out[0] = model.predict(X_features[-1].reshape(1, -1))[0]
    
    for i in range(1, te_len):
        # Check for divergence BEFORE feeding back
        if not (0 <= y_out[i-1] <= 1) or np.isnan(y_out[i-1]):
            return False # Divergence detected
        
        rho = input_map(rho, y_out[i-1],N)
        X_eval = np.zeros(N * V)
        for v in range(V):
            rho = evolve(rho, Phase_dt)
            rd = rho.diagonal()
            for n in range(N):
                X_eval[v*N + n] = np.real(np.sum(rd * z_diags[n]))
        
        y_out[i] = model.predict(((X_eval + 1) / 2).reshape(1, -1))[0]

    return True # Success: No divergence in 2000 steps

# --- 3. Main Execution ---
if __name__ == "__main__":
    N, J_val, tau, V = 7, 1, 4, 10
    h_values = np.logspace(-2, 2, 20)
    success_count = []
    n_realisations = 100
    n_cpus = int(os.environ.get('PBS_NP', os.cpu_count()))
    
    # Define lengths once here
    w_len, tr_len, te_len = 1000, 10000, 2000
    y_full = generate_mg_dataset()
    
    # Create the data tuple
    slices = (
        y_full[:w_len],                      # s_washout
        y_full[w_len : w_len+tr_len],        # s_train
        y_full[w_len+1 : w_len+tr_len+1],    # y_train (target)
        y_full[w_len+tr_len : w_len+tr_len+te_len] # y_test_target
    )
    print(f"Scanning h over {len(h_values)} points...")
    for h in h_values:
        results = Parallel(n_jobs=n_cpus)(
            delayed(run_stability_test)(h, seed, slices) 
            for seed in range(n_realisations))

        success_count.append(sum(results))
    
    np.savez("MG_Scan_over_h_val.npz", h_values = h_values, success_count = success_count, n_realisations=n_realisations, N=N, J=J_val, tau=tau, V=V, model="Ising_fully_connected")