import numpy as np
from scipy.linalg import eigh
from sklearn.kernel_ridge import KernelRidge
from Models import get_Pauli_X, get_Pauli_Z, Ising
from Density_matrix import trace_1, mixed_density_matrix
import sys


# --- 1. Parameters ---
N = 7          # Number of spins
J_val = 1      # Coupling strength
h_val = 0.5    # Transverse field
tau = 4        # Total time per step
V = 10         # Internal time steps (sub-sampling)
seed = 62
rng = np.random.default_rng(seed)
use_stabilization=True

# --- 2. Mackey-Glass Data Generation ---
sigma, tau_MG, steps = 0.1, 17, 140000
A = np.zeros(steps)
A[0] = 1.2
delay_idx = int(tau_MG / sigma)

for i in range(steps - 1):
    # Using 1.2 as history to avoid the fixed-point at 0
    delayed_val = A[i - delay_idx] if i >= delay_idx else 1.2
    A[i+1] = A[i] + sigma * ((0.2 * delayed_val) / (1 + delayed_val**10) - 0.1 * A[i])

# Subsample and shift data for the task
A = A[10000:] #discarding the first 10000 sub-steps
y = np.zeros(int(len(A)/10))
for k in range(len(y)):
    y[k] = A[k*10]
y = (y - min(y))/(max(y)-min(y))
y = 0.1 + 0.8*y # y in [0.1, 0.9]
print(f"y_max = {max(y)}; y_min = {min(y)}")
washout_len, train_len, test_len = 1000, 10000, 2000
s_washout = y[:washout_len]
s_train = y[washout_len:washout_len+train_len]
y_train = y[washout_len+1:washout_len+train_len+1]

# --- 3. Hamiltonian and Operator Setup ---
# Pre-calculate operators once using Models module
x_ops = get_Pauli_X(N)
z_ops = get_Pauli_Z(N)

# Construct the Ising Hamiltonian
Hamiltonian, _ = Ising(N, J_val, h_val, rng, x_ops, z_ops)

# --- 4. Exact Diagonalization (ED) for Time Evolution ---
# Diagonalizing once allows for extremely fast evolution in the inner loop
E, U = eigh(Hamiltonian)
U_dag = U.conj().T

# Pre-calculate phase matrix for the time step dt = tau/V
dt = tau / V
# Phase matrix: Phase[j,k] = exp(-1j * (Ej - Ek) * dt)
Phase = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * dt)
# Phase matrix for tau time directly
Phase_full_step = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * tau)


def evolve_step_ed(rho_comp):
    """Evolution using the energy basis to avoid expm calls."""
    rho_energy = U_dag @ rho_comp @ U
    rho_energy_evolved = rho_energy * Phase
    return U @ rho_energy_evolved @ U_dag

def evolve_full_step(rho_comp):
    rho_energy = U_dag @ rho_comp @ U
    rho_energy_evolved = rho_energy * Phase_full_step
    return U @ rho_energy_evolved @ U_dag

def input_map(rho_in, s, N):
    """Map input s to the first spin and trace out the rest using the module's reshape trick."""
    psi_s = np.array([np.sqrt(1-s), np.sqrt(s)], dtype=complex)
    rho_s = np.outer(psi_s, psi_s.conj())
    # Use optimized partial trace from Density_matrix
    rho_rest = trace_1(rho_in, N)
    return np.kron(rho_s, rho_rest)

# --- 5. Training Phase ---
# Initial mixed state generated by the module
rho = mixed_density_matrix(10, 2, N, rng)
X_features = np.zeros((train_len, N * V))

# Pre-calculate diagonals of Z for fast trace-less expectation values
z_diags = [op.diagonal() for op in z_ops]

print("Starting Washout Phase...")
for k in range(washout_len):
    rho = input_map(rho, s_washout[k], N)
    rho = evolve_full_step(rho)

print("Starting Training Phase...")
for k in range(train_len):
    rho = input_map(rho, s_train[k], N)
    for v in range(V):
        rho = evolve_step_ed(rho)
        # Fast expectation value: Tr(rho @ Z) = sum(diag(rho) * diag(Z))
        rho_diag = rho.diagonal()
        for n in range(N):
            X_features[k, v*N + n] = np.real(np.sum(rho_diag * z_diags[n]))

# Post-processing: Normalization and small noise for stability
X_features = (X_features + 1) / 2
X_features += rng.uniform(-1e-5, 1e-5, X_features.shape)

model = KernelRidge(kernel='rbf', gamma=0.1, alpha=1e-5).fit(X_features,y_train)

print("Training Complete.")

# --- 6. Evaluation Phase (One-step-ahead Prediction) ---
y_pred = np.zeros(test_len)
# Use the final training features to predict the first step
y_pred[0] = model.predict(X_features[-1].reshape(1, -1))[0]

print("Starting Evaluation Phase...")
for i in range(1, test_len):
    rho = input_map(rho, y_pred[i-1], N)
    X_eval = np.zeros(N * V)
    for v in range(V):
        rho = evolve_step_ed(rho)
        rd = rho.diagonal()
        for n in range(N):
            X_eval[v*N + n] = np.real(np.sum(rd * z_diags[n]))
    
    # Predict next step based on current reservoir state
    feat = ((X_eval + 1) / 2).reshape(1, -1)
    y_pred[i] = model.predict(feat)[0]
    
    # Check for divergence
    if not (0 <= y_pred[i] <= 1):
        print(f"Warning: Divergence detected at step {i}")
        sys.exit()

## NMSE
NMSE_val = np.sum((y_pred-y[washout_len+train_len:washout_len+train_len+test_len])**2)/np.sum(y[washout_len+train_len:washout_len+train_len+test_len:]**2)
print('NMSE_val =', NMSE_val)
print(f"Simulation Finished. Prediction range: {y_pred.min():.3f} to {y_pred.max():.3f}")

#if NMSE_val < 1e-1:
#    np.savez_compressed('Data/FN_MG_KerRid.npz', T = np.linspace(washout_len+train_len,washout_len+train_len+test_len-1, test_len), y_pred = y_pred, y_test = y[-test_len:], N_spins=N, J_val=J_val, h_val=h_val, tau=tau, V=V, model="Fully connected transverse field Ising model")