# MG task with FN.
# The code has been optimized.
# With Stabilization
# Memory and time consumption

import numpy as np
from scipy.linalg import eigh
from sklearn.linear_model import LinearRegression, Ridge
from Models import get_Pauli_X, get_Pauli_Z, J_matrix, FullyConnected_TFIM
from Density_matrix import trace_1, mixed_density_matrix
import time
import tracemalloc

tracemalloc.start()
start_time = time.perf_counter()


# --- 1. Parameters ---
N = 7          # Number of spins
J_val = 1      # Coupling strength
h_val = 0.5e-1    # Transverse field
tau = 10     # Total time per step
V = 10         # Internal time steps (sub-sampling)
seed = 42
rng = np.random.default_rng(seed)

# --- 2. Mackey-Glass Data Generation ---
sigma, tau_MG, steps = 0.1, 17, 140000
A = np.zeros(steps)
A[0] = 1.2
delay_idx = int(tau_MG / sigma)

for i in range(steps - 1):
    # Using 1.2 as history to avoid the fixed-point at 0
    delayed_val = A[i - delay_idx] if i >= delay_idx else 1.2
    A[i+1] = A[i] + sigma * ((0.2 * delayed_val) / (1 + delayed_val**10) - 0.1 * A[i])

# Subsample and shift data for the task
A = A[10000:] #discarding the first 10000 sub-steps
y = np.zeros(int(len(A)/10))
y = A[::10]
#for k in range(len(y)):
#    y[k] = A[k*10]
y = (y - min(y))/(max(y)-min(y))
#y = 0.1 + 0.8*y # y is now with in [0.1,0.9]
print(f"y_max = {max(y)}; y_min = {min(y)}")
washout_len, train_len, test_len = 1000, 10000, 2000
s_washout = y[:washout_len]
s_train = y[washout_len:washout_len+train_len]
y_train = y[washout_len+1:washout_len+train_len+1]

# --- 3. Hamiltonian and Operator Setup ---
# Pre-calculate operators once using Models module
x_ops = get_Pauli_X(N)
z_ops = get_Pauli_Z(N)

# Construct the Ising Hamiltonian
J_ij = J_matrix(N,-J_val/2,J_val/2,rng)
Hamiltonian, _ = FullyConnected_TFIM(N,J_ij,h_val)
Hamiltonian = Hamiltonian.toarray()

# --- 4. Exact Diagonalization (ED) for Time Evolution ---
# Diagonalizing once allows for extremely fast evolution in the inner loop
E, U = eigh(Hamiltonian)
U_dag = U.conj().T

# Pre-calculate phase matrix for the time step dt = tau/V
dt = tau / V
# Phase matrix: Phase[j,k] = exp(-1j * (Ej - Ek) * dt)
Phase_dt = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * dt)
# Phase matrix for tau time directly
Phase_tau = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * tau)


def evolve(rho_in, phase_mat):
        rho_energy = U_dag @ rho_in @ U
        return U @ (rho_energy * phase_mat) @ U_dag

def input_map(rho_in, s, N):
    """Map input s to the first spin and trace out the rest using the module's reshape trick."""
    psi_s = np.array([np.sqrt(s), np.sqrt(1-s)], dtype=complex)
    rho_s = np.outer(psi_s, psi_s.conj())
    rho_rest = trace_1(rho_in, N)
    return np.kron(rho_s, rho_rest)

# --- 5. Training Phase ---
# Initial mixed state generated by the module
#rho = mixed_density_matrix(10, 2, N, rng)
rho = np.full((2**N,2**N),1/2**N)   # maximally coherent density matrix
X_features = np.zeros((train_len, N * V))

# Pre-calculate diagonals of Z for fast trace-less expectation values
z_diags = [op.diagonal() for op in z_ops]

print("Starting Washout Phase...")
for k in range(washout_len):
    rho = evolve(input_map(rho, s_washout[k], N),Phase_tau)

print("Starting Training Phase...")
for k in range(train_len):
    rho = input_map(rho, s_train[k], N)
    for v in range(V):
        rho = evolve(rho,Phase_dt)
        # Fast expectation value: Tr(rho @ Z) = sum(diag(rho) * diag(Z))
        rho_diag = rho.diagonal()
        for n in range(N):
            X_features[k, v*N + n] = np.real(np.sum(rho_diag * z_diags[n]))

# Post-processing: Normalization and small noise for stability
X_features = (X_features + 1) / 2
X_features += rng.uniform(-1e-5, 1e-5, X_features.shape)

#model = Ridge(alpha=1e-4).fit(X_features, y_train)
model = LinearRegression().fit(X_features,y_train)
#joblib.dump(model, 'Data/linear_regression_model.pkl')
print("Training Complete.")

# --- 6. Evaluation Phase (One-step-ahead Prediction) ---
y_pred = np.zeros(test_len)
# Use the final training features to predict the first step
y_pred[0] = model.predict(X_features[-1].reshape(1, -1))[0]

print("Starting Evaluation Phase...")
for i in range(1, test_len):
    rho = input_map(rho, y_pred[i-1], N)
    X_eval = np.zeros(N * V)
    for v in range(V):
        rho = evolve(rho,Phase_dt)
        rd = rho.diagonal()
        for n in range(N):
            X_eval[v*N + n] = np.real(np.sum(rd * z_diags[n]))
    
    # Predict next step based on current reservoir state
    feat = ((X_eval + 1) / 2).reshape(1, -1)
    y_pred[i] = model.predict(feat)[0]
    
    # Check for divergence
    if not (0 <= y_pred[i] <= 1):
        print(f"Warning: Divergence detected at step {i}")
        break

## NMSE
NMSE_val = np.sum((y_pred-y[washout_len+train_len:washout_len+train_len+test_len])**2)/np.sum(y[washout_len+train_len:washout_len+train_len+test_len:]**2)
print('NMSE_val =', NMSE_val)
print(f"Simulation Finished. Prediction range: {y_pred.min():.3f} to {y_pred.max():.3f}")
np.savez_compressed('mg.npz',
                    pred = y_pred,
                    target = y[washout_len+train_len:],
                    time_steps = np.linspace(10000,11999,2000)
                    )


end_time = time.perf_counter()
current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

print(f"Total time: {end_time-start_time:.4f}s")
print(f"Peak RAM: {peak/10**6:.2f} MB")
print(f"Current RAM: {current/10**6:.2f} MB")