import numpy as np
from scipy.linalg import eigh
from sklearn.linear_model import LinearRegression, Ridge
from Models import get_Pauli_X, get_Pauli_Z, Ising
from Density_matrix import trace_1, mixed_density_matrix
import sys
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split

# --- 1. Parameters ---
N = 7          # Number of spins
J_val = 1      # Coupling strength
h_val = 0.5    # Transverse field
tau = 4        # Total time per step
V = 10         # Internal time steps (sub-sampling)
seed = 42
rng = np.random.default_rng(seed)
use_stabilization=True

# --- 2. Mackey-Glass Data Generation ---
sigma, tau_MG, steps = 0.1, 17, 140000
A = np.zeros(steps)
A[0] = 1.2
delay_idx = int(tau_MG / sigma)

for i in range(steps - 1):
    # Using 1.2 as history to avoid the fixed-point at 0
    delayed_val = A[i - delay_idx] if i >= delay_idx else 1.2
    A[i+1] = A[i] + sigma * ((0.2 * delayed_val) / (1 + delayed_val**10) - 0.1 * A[i])

# Subsample and shift data for the task
A = A[10000:] #discarding the first 10000 sub-steps
y = np.zeros(int(len(A)/10))
for k in range(len(y)):
    y[k] = A[k*10]
y = (y - min(y))/(max(y)-min(y))
if use_stabilization: 
    # y in [0.1,0.9]
    y = 0.1 + 0.8*y 
print(f"y_max = {max(y)}; y_min = {min(y)}")
washout_len, train_len, test_len = 1000, 10000, 2000
s_washout = y[:washout_len]
s_train = y[washout_len:washout_len+train_len]
y_train = y[washout_len+1:washout_len+train_len+1]

# --- 3. Hamiltonian and Operator Setup ---
# Pre-calculate operators once using Models module
x_ops = get_Pauli_X(N)
z_ops = get_Pauli_Z(N)

# Construct the Ising Hamiltonian
Hamiltonian, _ = Ising(N, J_val, h_val, rng, x_ops, z_ops)

# --- 4. Exact Diagonalization (ED) for Time Evolution ---
# Diagonalizing once allows for extremely fast evolution in the inner loop
E, U = eigh(Hamiltonian)
U_dag = U.conj().T

# Pre-calculate phase matrix for the time step dt = tau/V
dt = tau / V
# Phase matrix: Phase[j,k] = exp(-1j * (Ej - Ek) * dt)
Phase = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * dt)
# Phase matrix for tau time directly
Phase_full_step = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * tau)


def evolve_step_ed(rho_comp):
    """Evolution using the energy basis to avoid expm calls."""
    rho_energy = U_dag @ rho_comp @ U
    rho_energy_evolved = rho_energy * Phase
    return U @ rho_energy_evolved @ U_dag

def evolve_full_step(rho_comp):
    rho_energy = U_dag @ rho_comp @ U
    rho_energy_evolved = rho_energy * Phase_full_step
    return U @ rho_energy_evolved @ U_dag

def input_map(rho_in, s, N):
    """Map input s to the first spin and trace out the rest using the module's reshape trick."""
    psi_s = np.array([np.sqrt(1-s), np.sqrt(s)], dtype=complex)
    rho_s = np.outer(psi_s, psi_s.conj())
    # Use optimized partial trace from Density_matrix
    rho_rest = trace_1(rho_in, N)
    return np.kron(rho_s, rho_rest)

# --- 5. Training Phase ---
# Initial mixed state generated by the module
rho = mixed_density_matrix(10, 2, N, rng)
X_features = np.zeros((train_len, N * V))

# Pre-calculate diagonals of Z for fast trace-less expectation values
z_diags = [op.diagonal() for op in z_ops]

print("Starting Washout Phase...")
for k in range(washout_len):
    rho = input_map(rho, s_washout[k], N)
    rho = evolve_full_step(rho)

print("Starting Training Phase...")
for k in range(train_len):
    rho = input_map(rho, s_train[k], N)
    for v in range(V):
        rho = evolve_step_ed(rho)
        # Fast expectation value: Tr(rho @ Z) = sum(diag(rho) * diag(Z))
        rho_diag = rho.diagonal()
        for n in range(N):
            X_features[k, v*N + n] = np.real(np.sum(rho_diag * z_diags[n]))

# Post-processing: Normalization and small noise for stability
X_features = (X_features + 1) / 2
X_features += rng.uniform(-1e-5, 1e-5, X_features.shape)

#--------------- MLP at the readout layer  -----------------------------------
class QuantumReadoutMLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(QuantumReadoutMLP, self).__init__()
        # Small MLP Architecture
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), # Input: Number of observables
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim), # Optional second layer
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim)  # Output: Task dependent
        )
        
    def forward(self, x):
        return self.network(x)

# Example: 10 qubits with Z-measurements = 10 inputs
model = QuantumReadoutMLP(input_dim=N*V, hidden_dim=32, output_dim=1)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

def predict_single(sample_array, model):
    """
    sample_array: a single reservoir state (e.g., a list or 1D numpy array)
    """
    model.eval()
    with torch.no_grad():
        # 1. Convert to tensor
        sample_tensor = torch.tensor(sample_array, dtype=torch.float32)
        
        # 2. Add batch dimension: (input_dim) -> (1, input_dim)
        sample_tensor = sample_tensor.unsqueeze(0)
        
        # 3. Predict
        prediction = model(sample_tensor)
        
        # 4. Return as a scalar or list
        return prediction.item()

# Split data: 80% Training, 20% Validation
X_train, X_val, y_train, y_val = train_test_split(
    X_features, y_train, test_size=0.2, random_state=42
)

# --- Updated Tensor Conversion ---
# Convert to Tensors and ensure they are (N, 1) instead of (N,)
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1) # Added .view(-1, 1)

X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)     # Added .view(-1, 1)

# Create a dataset and loader for batching
dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(dataset, batch_size=32, shuffle=True)

# Hyperparameters
num_epochs = 500


for epoch in range(num_epochs):
    model.train() # Set model to training mode
    epoch_loss = 0.0
    for batch_X, batch_y in train_loader:
        # 1. Forward pass
        predictions = model(batch_X)
        loss = criterion(predictions, batch_y)
        
        # 2. Backward pass (the "learning" part)
        optimizer.zero_grad() # Clear previous gradients
        loss.backward()        # Calculate new gradients
        optimizer.step()       # Update weights
        
        epoch_loss += loss.item()
    
    # Validation Check
    model.eval()
    with torch.no_grad():
        val_preds = model(X_val_tensor)
        val_loss = criterion(val_preds, y_val_tensor)
    
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: Train Loss: {epoch_loss/len(train_loader):.4f} | Val Loss: {val_loss.item():.4f}")

#torch.save(model.state_dict(), 'Data/mlp_weights.pth')

# Usage:
#new_reservoir_state = X_features[0] # Just an example sample
#result = predict_single(new_reservoir_state, model)
#print(f"The model's prediction for this state is: {result}")
#print(f"The actual value is {y[washout_len+1]}.")

# --- 6. Evaluation Phase (One-step-ahead Prediction) ---
y_pred = np.zeros(test_len)
# Use the final training features to predict the first step
y_pred[0] = predict_single(X_features[-1],model)

print("Starting Evaluation Phase...")
for i in range(1, test_len):
    rho = input_map(rho, y_pred[i-1], N)
    X_eval = np.zeros(N * V)
    for v in range(V):
        rho = evolve_step_ed(rho)
        rd = rho.diagonal()
        for n in range(N):
            X_eval[v*N + n] = np.real(np.sum(rd * z_diags[n]))
    
    # Predict next step based on current reservoir state
    feat = ((X_eval + 1) / 2).reshape(1, -1)
    y_pred[i] = predict_single(feat,model)
    
    # Check for divergence
    if not (0 <= y_pred[i] <= 1):
        print(f"Warning: Divergence detected at step {i}")
        sys.exit()

## NMSE
NMSE_val = np.sum((y_pred-y[washout_len+train_len:washout_len+train_len+test_len])**2)/np.sum(y[washout_len+train_len:washout_len+train_len+test_len:]**2)
print('NMSE_val =', NMSE_val)
print(f"Simulation Finished. Prediction range: {y_pred.min():.3f} to {y_pred.max():.3f}")


