# MG task with FN.
# The code has been optimized.
# Comparison of performance between stabilized and not stabilized code.
# By stabilization is meant two changes: (1) y in [0.1,0.9]; and (2) Ridge Regression.

import numpy as np
import os
from joblib import Parallel, delayed
from scipy.linalg import eigh
from sklearn.linear_model import LinearRegression, Ridge
from Models import get_Pauli_X, get_Pauli_Z, Ising
from Density_matrix import trace_1, mixed_density_matrix
import resource

# --- 1. Simulation Logic ---
def run_stability_test(seed, use_margin=True, use_Ridge=True):
    # Parameters
    N, J_val, h_val, tau, V = 7, 1, 0.5, 4, 10
    washout_len, train_len, test_len = 1000, 10000, 2000
    rng = np.random.default_rng(seed)

    # Data Generation (Mackey-Glass)
    sigma, tau_MG, steps = 0.1, 17, 140000
    A = np.zeros(steps)
    A[0] = 1.2
    delay_idx = int(tau_MG / sigma)

    for i in range(steps - 1):
        # Using 1.2 as history to avoid the fixed-point at 0
        delayed_val = A[i - delay_idx] if i >= delay_idx else 1.2
        A[i+1] = A[i] + sigma * ((0.2 * delayed_val) / (1 + delayed_val**10) - 0.1 * A[i])

    # Subsample and shift data for the task
    A = A[10000:] #discarding the first 10000 sub-steps
    y = np.zeros(int(len(A)/10))
    for k in range(len(y)):
        y[k] = A[k*10]
    y = (y - min(y))/(max(y)-min(y))
    if use_margin:
        # Scale to [0.1, 0.9] for safety
        y = 0.1 + 0.8 *y
    
    s_washout = y[:washout_len]
    s_train = y[washout_len:washout_len+train_len]
    y_train = y[washout_len+1:washout_len+train_len+1]

    # --- 3. Hamiltonian and Operator Setup ---
    # Pre-calculate operators once using Models module
    x_ops = get_Pauli_X(N)
    z_ops = get_Pauli_Z(N)

    # Construct the Ising Hamiltonian
    Hamiltonian, _ = Ising(N, J_val, h_val, rng, x_ops, z_ops)

    # --- 4. Exact Diagonalization (ED) for Time Evolution ---
    # Diagonalizing once allows for extremely fast evolution in the inner loop
    E, U = eigh(Hamiltonian)
    U_dag = U.conj().T

    # Pre-calculate phase matrix for the time step dt = tau/V
    dt = tau / V
    # Phase matrix: Phase[j,k] = exp(-1j * (Ej - Ek) * dt)
    Phase = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * dt)
    # Phase matrix for tau time directly
    Phase_full_step = np.exp(-1j * (E[:, np.newaxis] - E[np.newaxis, :]) * tau)


    def evolve_step_ed(rho_comp):
        """Evolution using the energy basis to avoid expm calls."""
        rho_energy = U_dag @ rho_comp @ U
        rho_energy_evolved = rho_energy * Phase
        return U @ rho_energy_evolved @ U_dag

    def evolve_full_step(rho_comp):
        rho_energy = U_dag @ rho_comp @ U
        rho_energy_evolved = rho_energy * Phase_full_step
        return U @ rho_energy_evolved @ U_dag

    def input_map(rho_in, s, N):
        """Map input s to the first spin and trace out the rest using the module's reshape trick."""
        psi_s = np.array([np.sqrt(1-s), np.sqrt(s)], dtype=complex)
        rho_s = np.outer(psi_s, psi_s.conj())
        # Use optimized partial trace from Density_matrix
        rho_rest = trace_1(rho_in, N)
        return np.kron(rho_s, rho_rest)

    # --- 5. Training Phase ---
    # Initial mixed state generated by the module
    rho = mixed_density_matrix(10, 2, N, rng)
    X_features = np.zeros((train_len, N * V))

    # Pre-calculate diagonals of Z for fast trace-less expectation values
    z_diags = [op.diagonal() for op in z_ops]

    for k in range(washout_len):
        rho = input_map(rho, s_washout[k], N)
        rho = evolve_full_step(rho)

    for k in range(train_len):
        rho = input_map(rho, s_train[k], N)
        for v in range(V):
            rho = evolve_step_ed(rho)
            # Fast expectation value: Tr(rho @ Z) = sum(diag(rho) * diag(Z))
            rho_diag = rho.diagonal()
            for n in range(N):
                X_features[k, v*N + n] = np.real(np.sum(rho_diag * z_diags[n]))

    # Post-processing: Normalization and small noise for stability
    X_features = (X_features + 1) / 2
    X_features += rng.uniform(-1e-5, 1e-5, X_features.shape)

    if use_Ridge:
        model = Ridge(alpha=1e-4).fit(X_features, y_train)
    else:
        model = LinearRegression().fit(X_features, y_train)

    # --- Evaluation (The Probe) ---
    y_out = np.zeros(test_len)
    y_out[0] = model.predict(X_features[-1].reshape(1, -1))[0]
    
    for i in range(1, test_len):
        # Check for divergence BEFORE feeding back
        if not (0 <= y_out[i-1] <= 1) or np.isnan(y_out[i-1]):
            return False # Divergence detected
        
        rho = input_map(rho, y_out[i-1],N)
        X_eval = np.zeros(N * V)
        for v in range(V):
            rho = evolve_step_ed(rho)
            rd = rho.diagonal()
            for n in range(N):
                X_eval[v*N + n] = np.real(np.sum(rd * z_diags[n]))
        
        y_out[i] = model.predict(((X_eval + 1) / 2).reshape(1, -1))[0]

    return True # Success: No divergence in 2000 steps

# --- 2. Main Execution ---
if __name__ == "__main__":
    n_realisations = 100
    n_cpus = int(os.environ.get('SLURM_CPUS_PER_TASK', 1))

    print(f"Probing stability over {n_realisations} realisations...")
    
    # Run Stabilized Version
    results = Parallel(n_jobs=n_cpus, verbose=10)(
        delayed(run_stability_test)(seed, use_margin=True, use_Ridge=False) 
        for seed in range(n_realisations)
    )

    success_count = sum(results)
    print("\n--- RESULTS ---")
    print(f"Total Realisations: {n_realisations}")
    print(f"Successful Runs:   {success_count}")
    print(f"Divergence Rate:   {(n_realisations - success_count) / n_realisations:.2%}")
    print(f"Success Fraction:   {success_count / n_realisations:.2%}")

    # Get peak memory usage in kilobytes
    usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

    # Convert to Megabytes or Gigabytes
    print(f"--- Resource Usage Report ---")
    print(f"Peak Memory Usage: {usage / 1024:.2f} MB")
